### ISSUE TITLE
web3js.eth.getBalance not support on this provider

### ISSUE THREAD

**Issue by sebkim** [loomnetwork/loom-js#136]
i call below:

web3js.eth.getBalance(account).then(console.log)
  .catch(err => console.log(err))

on plasmaChain testNet with recent loom-js@1.29.1

but error occurs saying below:

Error: Method "eth_getBalance" not supported on this provider

now testnet plasmaChain not support ETH?

**Comment by eduardonunesp** [comment]
hey @sebkim thanks for your report, we fixed this on the current `beta` version, check out our `README.md`, you can get the `beta` version using the command `yarn add loom-js@beta` or `npm install loom-js@beta`
