### ISSUE TITLE
snyk scan find the high severity vulnerability issue for library shelljs

### ISSUE THREAD

**Issue by leapming** [loomnetwork/loom-js#172]
shelljs has known security issue

https://github.com/shelljs/shelljs/issues/766

**Comment by lukezhangstudio** [comment]
according to that thread in the shelljs repo, it's a known issue. But the vulernability is limited in scope, i'll audit our code and see if we are using any dangerous functions.

**Comment by eduardonunesp** [comment]
Loom-js isn't affected by the issue, the scope is very limited only calling `shell.exec` on the tooling for the build process, guaranteed that no `shell.exec` will be published on any package

- Places where used `shell.exec` https://github.com/loomnetwork/loom-js/blob/master/scripts/gen-proto.js#L38
