### ISSUE TITLE
Add bindings for recovering lost tokens

### ISSUE THREAD

**Issue by gakonst** [loomnetwork/loom-js#204]
Need bindings for the https://github.com/loomnetwork/loomchain/blob/master/builtin/plugins/gateway/gateway.go#L861 and https://github.com/loomnetwork/loomchain/blob/master/builtin/plugins/gateway/gateway.go#L820 functionalities. Also e2e tests.

**Comment by eduardonunesp** [comment]
Here is the PR https://github.com/loomnetwork/loom-js/pull/206, there's no e2e test yet, need some time to setup gateway test on e2e (there's no tg setup ready now)

**Comment by enlight** [comment]
Resolved
