### ISSUE TITLE
DPOSv3 Bindings

### ISSUE THREAD

**Issue by gakonst** [loomnetwork/loom-js#243]
TODO; Add bindings for all dpos-v3 contracts, 

AND 

refactor dpos-user into crosschain-gateway-user + dpos features.

dpos-user will just use features frmo gateway-user while maintaining 100% backwards compatibility.

**Comment by enlight** [comment]
And we need loom-js tests for the DPOSv3 API, the current DPOS tests are only for v1 so they're useless at this point, and I'll be disabling them.

**Comment by enlight** [comment]
I believe this has been done.
