### ISSUE TITLE
TypeError: Cannot read property 'MarshalPB' of undefined when interacting with solidity contracts

### ISSUE THREAD

**Issue by jdowning100** [loomnetwork/loom-js#259]
For some reason I'm unable to interact with my contracts after deploying with truffle. I'm getting numerous UnhandledPromiseRejectionWarning errors (which are basically runtime errors) from loom-js functions.
Code: 
```
(async function(){

	const client = new Client(
		'default',
		'ws://127.0.0.1:46658/websocket',
		'ws://127.0.0.1:46658/queryws',
	  )
	  
	const privateKey = CryptoUtils.generatePrivateKey()
	const publicKey = CryptoUtils.publicKeyFromPrivateKey(privateKey)
	client.txMiddleware = [
	  new NonceTxMiddleware(publicKey, client),
	  new SignedTxMiddleware(privateKey)
	]
	
	
	const web3 = new Web3(new LoomProvider(client, privateKey))

 let contracthardcoded = Address.fromString("default:0x707390e456C1fbf7286846C461Eb39918e982579")
 //let contractAddr = await client.getContractAddressAsync('SimpleStore')
 

  const callerAddr = new Address(client.chainId, LocalAddress.fromPublicKey(publicKey))
  const contract = new Contract({ contracthardcoded, callerAddr, client })
  const msgKey = '123'
  const msgValue = '456'
  const msg = new MapEntry()
  msg.setKey(msgKey)
  msg.setValue(msgValue)
  let ret = await contract.callAsync("testSender", msg)
  console.log(ret)

})()
````
Smart contract function I'm calling:
```
event newSender(address sender);
address public sender;
function testSender() public {
       sender = msg.sender;
       emit newSender(msg.sender);
    }
```

Result:
TypeError: Cannot read property 'MarshalPB' of undefined
at Contract.<anonymous> (/home/jonathan/loom-backend/node_modules/loom-js/dist/contract.js:80:50)
    at step (/home/jonathan/loom-backend/node_modules/tslib/tslib.js:133:27)
    at Object.next (/home/jonathan/loom-backend/node_modules/tslib/tslib.js:114:57)

If I uncomment the 'let contractAddr' I get {"code":-32603,"message":"Internal error","data":"name is not registered"}

I tried using web3 and was equally as unfruitful. Trying `web3.eth.sendSignedTransaction()` returns "eth_chainId not supported on this provider" and `await contract.methods.someFunction().send()` results in "Ineffective mark-compacts near heap limit Allocation failed - JavaScript heap out of memory". 
I am unable to interact with any smart contract deployed on my local chain due to these errors - please help. Thanks.

Loom version: 2.0.0+b789
Loom-js: 1.47.0
Web3: 1.0.0-beta.52

**Comment by jdowning100** [comment]
Also, the tutorial for Web3 in the documentation is outdated/does not work.
```
	const client = new Client(
		'default',
		'ws://127.0.0.1:46658/websocket',
		'ws://127.0.0.1:46658/queryws',
	  )
	  
	const privateKey = CryptoUtils.generatePrivateKey()
	const publicKey = CryptoUtils.publicKeyFromPrivateKey(privateKey)
	client.txMiddleware = [
	  new NonceTxMiddleware(publicKey, client),
	  new SignedTxMiddleware(privateKey)
	]
	const web3 = new Web3(new LoomProvider(client, privateKey))
	const from = LocalAddress.fromPublicKey(publicKey).toString()

	const contract = new web3.eth.Contract(abi, contractAddress, {from})
	console.log(contract.methods);
	console.log(from)
	let tx = await contract.methods.testSender().send()
	console.log(tx)
```
Result: 

 0: ExitFrame [pc: 0x3b22707cfc5d]
Security context: 0x3921e459d9d1 <JSObject>
    1: /* anonymous */(aka /* anonymous */) [0x3af84a751751] [/home/jonathan/loom-backend/node_modules/web3-core-method/dist/web3-core-method.cjs.js:~1110] [pc=0x3b2270d2f4c7](this=0x3fe5f9d825b1 <undefined>,0x3fe5f9d822a1 <null>)
    2: StubFrame [pc: 0x3b22707bf8ae]
    3: StubFrame [pc: 0x3b227079c6d2]
    4: EntryFrame [pc: 0x3b2270785c7e]
    5: ExitFra...

FATAL ERROR: Ineffective mark-compacts near heap limit Allocation failed - JavaScript heap out of memory

**Comment by enlight** [comment]
Which tutorial is this from?

**Comment by jdowning100** [comment]
The functions in the first post are used [here](https://loomx.io/developers/docs/en/loom-js-quickstart.html#connecting-to-a-dappchain) and in the second post [here](https://loomx.io/developers/docs/en/web3js-loom-provider-truffle.html#adding-to-project-and-configuring). Please either update the documentation or explain to me what I'm doing wrong.
Thanks.

**Comment by jdowning100** [comment]
> Which tutorial is this from?

**Comment by jdowning100** [comment]
Accidentally closed

**Comment by enlight** [comment]
This example https://loomx.io/developers/docs/en/loom-js-quickstart.html#connecting-to-a-dappchain shows how to interact with a Go contract on the DAppChain, you're trying to interact with an EVM contract so it's not relevant.

This should work https://github.com/loomnetwork/loom-js/issues/259#issuecomment-481868077 but you may need to downgrade web3 to beta 34.

**Comment by jdowning100** [comment]
> This example https://loomx.io/developers/docs/en/loom-js-quickstart.html#connecting-to-a-dappchain shows how to interact with a Go contract on the DAppChain, you're trying to interact with an EVM contract so it's not relevant.
> 
> This should work [#259 (comment)](https://github.com/loomnetwork/loom-js/issues/259#issuecomment-481868077) but you may need to downgrade web3 to beta 34.

Thank you for your reply. Downgrading to web3 beta 34 worked. I didn't know web3 introduced breaking changes in their new version, and I'm not sure why npm decided to install the latest beta (some dependency probably). 
Also, as a side-issue: ecrecover() assumes the Ethereum elliptic curve, not the Loom one. Using a loom address with ecerecover() will not work.
I'm closing this issue.
