### ISSUE TITLE
Provide support for user deployer whitelist contract in loom.js

### ISSUE THREAD

**Issue by sidharth747** [loomnetwork/loom-js#271]

**Comment by enlight** [comment]
UserDeployerWhitelist contract binding should unmarshal the responses from the contract so the caller doesn't have to.

This should return `Array<IDeployer>` where `IDeployer` is an interface of the unmarshalled deployer info.
https://github.com/loomnetwork/loom-js/blob/21f91854629b52b71c393bd6619c45e7f6dc9b12/src/contracts/user-deployer-whitelist.ts#L53

This should return `Array<IDeployedContract> where `IDeployedContract` is an interface of the unmarshalled contract info.
https://github.com/loomnetwork/loom-js/blob/21f91854629b52b71c393bd6619c45e7f6dc9b12/src/contracts/user-deployer-whitelist.ts#L68

**Comment by enlight** [comment]
Resolved
