### ISSUE TITLE
User-constructed Address doesn't match Address type in NonceTxMiddleware Classes

### ISSUE THREAD

**Issue by robmyers** [loomnetwork/loom-js#289]
Heya.

In the NonceTxMiddleware classes the constructors take either a public key or an address and check for type loom_pb.Address to determine which they are storing, e.g:

https://github.com/loomnetwork/loom-js/blob/a8ee593616dcc276f76a1cb125512732f8d7d7c4/src/middleware/speculative-nonce-tx-middleware.ts#L29

But if I construct a loom-js.Address in JavaScript and pass it in to the middleware constructor, that is a different type and doesn't match. So the Middleware therefore stores the Address as a public key, which causes errors when trying to fetch the nonce.

I can subclass the middleware to just use a loom-js.Address, e.g.:
```
class AddressSpeculativeNonceTxMiddleware extends SpeculativeNonceTxMiddleware {
  constructor(account, client) {
    super(account, client);
    delete this._publicKey;
    this._account = account;
  }
}
```

So it *looks* like this should work with loom-js.Address.

Given this, it looks like:

    import { NonceTx, Address } from '../proto/loom_pb'

should be:

    import { NonceTx } from '../proto/loom_pb'
    import { Address } from '../address'

If I am misreading this (I'm not a TypeScript expert), how should I be making the loom_pb.Address to pass in to the middleware?

Thank you.

**Comment by redben** [comment]
Correct. It should be Address. This has been fixed in 
[1.57.3](https://github.com/loomnetwork/loom-js/tree/v1.57.3).

**Comment by robmyers** [comment]
That's great, thank you!
