### ISSUE TITLE
When will this be live?

### ISSUE THREAD

**Issue by elie222** [loomnetwork/loom-js#3]
Looks really exciting!

Two things I'm wondering:
1) When will this go live?
2) When will the README updated to get started with this? Happy to contribute on this front too.

**Comment by mattkanwisher** [comment]
Its already in private beta, you can signup http://bit.ly/LoomSDK 
We will be launching to larger audience soon

**Comment by EddieOne** [comment]
I see some recent code. Is it ready to use? We signed up for the private beta but didn't receive a response.

**Comment by mattkanwisher** [comment]
Hey we are sending out more update emails on Monday. I'll have someone reach out to you directly to get you on boarded to the beta
