### ISSUE TITLE
LoomProvider or EvmContract

### ISSUE THREAD

**Issue by Oxyaction** [loomnetwork/loom-js#32]
According to the doc page, EvmContract is recommended way to communicate with evm contracts
https://loomx.io/developers/docs/en/evm.html#loom-js
But as I saw in https://github.com/loomnetwork/tiles-chain-evm demo
**LoomProvider** is more friendly way to do it since it utilizes the web3 contract API and
doesn't require binary encoded transaction data.

Unfortunately, it uses **WebSocket** class that is absent in node environment.
It would be great to adopt some isomorphic websocket solution, for example
https://www.npmjs.com/package/isomorphic-ws

**Comment by enlight** [comment]
Thanks for your suggestion, Node support in LoomProvider is already planned for the next release.

**Comment by Oxyaction** [comment]
Thanks for response, waiting for the next versions 👍.
