### ISSUE TITLE
Modules/Export warnings on tsc compile

### ISSUE THREAD

**Issue by ACatThatPrograms** [loomnetwork/loom-js#64]
Typescript compiling is throwing some errors for me.

I'm not sure if these components are critical components to loom-js running, though as I am shifting to typescript I got these errors when compiling with tsc in my own team's project utilizing loom.

I went ahead and created a new project to install the latest loom-js module via npm and see if I got the same errors, which I did.

Software versions:

`npm -version` :: 5.6.0
`tsc -version` :: 2.9.2
loom-js is most recent npm module as of 7-24-2018

Reproduction:

1. "npm init" clean directory
2. "yarn add loom-js" or "npm install loom-js"
3. Create simple server.ts with the following:

````javascript
/// <reference path="./node_modules/loom-js/dist/index.d.ts" />

console.log("server.js ran.");
````

on `tsc server.ts` the following output is produced : 

Errors produced on tsc compile:

    $ tsc server.ts
    node_modules/loom-js/dist/client.d.ts(3,8): error TS1192: Module '"events"' has no default export.
    node_modules/loom-js/dist/contract.d.ts(3,26): error TS2307: Cannot find module 'event'.
    node_modules/loom-js/dist/evm-contract.d.ts(2,8): error TS1192: Module '"events"' has no default export.
    node_modules/loom-js/dist/internal/json-rpc-client.d.ts(2,8): error TS1192: Module '"events"' has no default export.
    node_modules/loom-js/dist/loom-provider.d.ts(56,24): error TS2304: Cannot find name 'Map'.

**Comment by enlight** [comment]
I haven't used reference paths in ages, loom-js is compiled to commonjs modules which you should load via `require` or `import`. For an example you can take a look at the Loom Truffle Provider https://github.com/loomnetwork/loom-truffle-provider/blob/master/src/index.ts#L1
