### ISSUE TITLE
Type error in forked repo

### ISSUE THREAD

**Issue by paulbarclay** [loomnetwork/loom-js#66]
Just forked the loom-js repo (need the ability to manage nonces on our server), and I'm getting one error. Any ideas?
```
src/plasma-cash/plasma-cash-tx.ts:45:30 - error TS2345: 
      Type 'Buffer' is not assignable to type 'EncodeScalarInput'.
        Type 'Buffer' is not assignable to type 'import("safe-buffer").Buffer'.
          Property 'prototype' is missing in type 'Buffer'.
45     return '0x' + rlp.encode(data).toString('hex')
```
(not a blocker; I can edit out the line for now, and everything builds fine)

**Comment by eduardonunesp** [comment]
@paulbarclay does the issue persists?

**Comment by paulbarclay** [comment]
Yes, nothing appears to be changed after merging the latest commit. If it's working in pure JS, it's a bit of a miracle - `rlp.encode(data)` uses the Buffer class from "safe-buffer", but the Buffer in `this.slot.toArrayLike(Buffer as any, 'be') as Buffer,` is the Buffer interface from Node. They're almost identical, but they're not set up the same, they don't inherit the and they don't have all the same fields.
