### ISSUE TITLE
ND - loom-js fails to capture both events emitted by solidity contract function

### ISSUE THREAD

**Issue by Nayeem1516** [loomnetwork/loom-js#82]
### Background:
Ben, [14.08.18 02:27]
Okay, I think I've got it. So, we have a solidity contract function that emits two events on minting a new token, but only one is captured (not both) by loom-js

Ben, [14.08.18 02:28]
function createCharacter(bytes32 _characterName) external whenNotPaused {
 require(_characterName != 0x0);
 require(characterNames[_characterName] == 0);
 uint256 id = nextId();
 characters[id] = _characterName;
 characterNames[_characterName] = id;
 characterStates[id] = CharacterState.Available;
 emit CharacterCreated(id);
 _mint(msg.sender, id);
}

Ben, [14.08.18 02:29]
So, we have our own custom event (CharacterCreated) and then one is automatically sent out from _mint

Ben, [14.08.18 02:30]
Depending on the order of the events, whichever comes first is captured, but the second event isn't caught

Ben, [14.08.18 02:32]
We've upgraded our loom javascript packages to the latest, and we're using build 375

Nayeem Siddique, [14.08.18 02:33]
Cool. Appreciate it. Ping me if you have more details to add anytime. Thanks

**Comment by eduardonunesp** [comment]
https://github.com/loomnetwork/loom-js/pull/84

**Comment by timothywangdev** [comment]
is this fixed? Currently using "loom-js": "^1.30.2", still have the same issue.

**Comment by eduardonunesp** [comment]
@such could you please confirm if this PR reproduces the error `https://github.com/loomnetwork/loom-js/pull/89`
