### ISSUE TITLE
getBlock & getBlockNumber produce odd results

### ISSUE THREAD

**Issue by paulbarclay** [loomnetwork/loom-js#83]
I've got a loom test chain running on AWS (single node). 

I can see it and make http calls to it at: http://52.88.113.238:46658/rpc. 

Contracts are deployed on it, and I can change their state, but, I can't see it in the loom block explorer (separate issue, maybe). I can put the block explorer address into a browser and read the json, though. 

What’s most odd is that the block height doesn’t seem to match reality. I see `web3.eth.getBlockNumber()` returning 2.2million, and both the block explorer json and the `web3.eth.getBlock(‘latest’)` giving 210k (210k is correct; it’s been running over the w/e
Also, getBlock doesn’t seem to return a proper “Block” obect - it has `blockNumber`, but no `number`

Further, the returned data from `web3.eth.getBlock()` is wrong; I get the following, not a proper Block object: ```{"blockNumber":"0x34fa2","transactionHash":"0xdee07e7f845caf52c76c0a30e762a03214455ee2","parentHash":"0x625965193b355527ed51550023694249768d091e","logsBloom":"0x","timestamp":1534198065,"transactions":[]}```
The data does appear to be correct, just formatted incorrectly.

**Comment by eduardonunesp** [comment]
Thanks @paulbarclay we'll going to check

**Comment by paulbarclay** [comment]
More oddness with getBlock: If you try a numerical getBlock in a block with a transaction, the getBlock fails with a BigNumber error (Something's undefined).

On that same server, the following calls might work or not:
loomWeb3.eth.getBlock(217777) > success
loomWeb3.eth.getBlock(217778) > fails
loomWeb3.eth.getBlock(217779) > success

Error log (we've added logging into loom_provider, so line numbers might not match):
```
Error: Error: [number-to-bn] while converting number undefined to BN.js instance, error: invalid number value. Value must be an integer, hex string, BN or BigNumber instance. Note, decimals are not supported. Given value: "undefined"
server_1  | [worker]     at Object.toBN (/srv/server/node_modules/web3-utils/src/utils.js:64:15)
server_1  | [worker]     at outputBigNumberFormatter (/srv/server/node_modules/web3-core-helpers/src/formatters.js:39:18)
server_1  | [worker]     at outputTransactionFormatter (/srv/server/node_modules/web3-core-helpers/src/formatters.js:176:19)
server_1  | [worker]     at /srv/server/node_modules/web3-core-helpers/src/formatters.js:251:24
server_1  | [worker]     at Array.forEach (<anonymous>)
server_1  | [worker]     at Method.outputBlockFormatter [as outputFormatter] (/srv/server/node_modules/web3-core-helpers/src/formatters.js:249:28)
server_1  | [worker]     at Method.formatOutput (/srv/server/node_modules/web3-core-method/src/index.js:163:54)
server_1  | [worker]     at sendTxCallback (/srv/server/node_modules/web3-core-method/src/index.js:476:33)
server_1  | [worker]     at /srv/server/node_modules/web3-core-requestmanager/src/index.js:147:9
server_1  | [worker]     at LoomProvider.<anonymous> (/srv/server/node_modules/loom-js/dist/loom-provider.js:250:25)
server_1  | [worker]     at step (/srv/server/node_modules/loom-js/dist/loom-provider.js:32:23)
server_1  | [worker]     at Object.f [as next] (/srv/server/node_modules/loom-js/dist/loom-provider.js:13:53)
server_1  | [worker]     at fulfilled (/srv/server/node_modules/loom-js/dist/loom-provider.js:4:58)
server_1  | [worker]     at <anonymous>
server_1  | [worker]     at process._tickCallback (internal/process/next_tick.js:188:7)

```

**Comment by paulbarclay** [comment]
More info: `getBlock(blockHash)` can be called, but times out after 15s. It does show up in logs as calling `eth_getBlockByHash`, and there's an error `http: proxy error: context canceled` in the server logs. (note: you have to edit @types/web3 to allow hash strings).

**Comment by alejoamiras** [comment]
This is happening to me too, and it _appears_ to be kinda random. But I can't get the information of some certain blocks (on ext-dev & local networks).

**Comment by eduardonunesp** [comment]
Fixed on https://github.com/loomnetwork/loom-js/pull/192, https://github.com/loomnetwork/loom-js/pull/191 and https://github.com/loomnetwork/vue-block-explorer/pull/20
